#********************
# 水平分表
#********************
spring:
  shardingsphere:
    datasource:
      names: ds-sharding
      ds-sharding:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ds_sharding_0
        username: root
        password: root
    #（★）分表
    sharding:
      #（▲）表定义
      tables:
        #（※）命名需要和表名一致！！！
        user_base:
          #（1）逻辑表
          logic-table: user_base
          #（2）实际数据节点
          #数据源名+表名组成，以小数点分隔；多个表以逗号分隔；支持inline表达式
          actual-data-nodes: ds-sharding.user_base_$->{0..1}
          #（3）分表策略
          table-strategy:
            inline:
              sharding-column: ub_user_id
              algorithm-expression: user_base_$->{ub_user_id % 2}
      #（▲）表绑定
      binding-tables:
        - user_base
    props:
      sql.show: false
      sql.simple: true