#********************
# 读写分离
#********************
spring:
  shardingsphere:
    #（★）数据源定义
    datasource:
      #（※）数据源命名，不能为空！！！
      names: ds-master,ds-slave0,ds-slave1
      #物理数据源，名称必须符合yml的key规则，使用 驼峰 或 -分隔符！
      ds-master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ds_sharding_0
        username: root
        password: root
      ds-slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ds_sharding_0
        username: root
        password: root
      ds-slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ds_sharding_0
        username: root
        password: root
    #（★）主从定义
    masterslave:
      #（※）逻辑数据源名称，为空时不执行读写分离！！！
      name: ds_ms
      #（1）主数据源
      master-data-source-name: ds-master
      #（2）从数据源
      slave-data-source-names:
        - ds-slave0
        - ds-slave1
      #（3）负载均衡，round_robin/random
      load-balance-algorithm-type: round_robin
    #（★）属性
    props:
      #日志内容包含：逻辑 SQL，真实 SQL 和 SQL 解析结果
      sql.show: true
      #打印简单风格的 SQL
      sql.simple: true
