#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-springboot-shardingjdbc
  main:
    web-application-type: none
    banner-mode: off
  #
  profiles:
#    active: master-slave
    active: sharding-table
#    active: sharding-algorithm
#
mybatis:
  mapper-locations: study/sharding/springboot/shardingjdbc/dao/**/**.xml
  type-aliases-package: study.sharding.springboot.shardingjdbc.dao